
sudo: false

cache:
  pip: true
  directories:
    - $HOME/.cache/pip
    - node_modules

language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy

env:
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'
  - DJANGO='django>=1.10,<1.11'
  - DJANGO='django>=1.9,<1.10'
  - DJANGO='django>=1.8,<1.9'

install:
  - npm install
  - pip install -r requirements/travis.pip
  - pip install $DJANGO

matrix:
  exclude:
    - python: 3.3
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: 3.3
      env: DJANGO='django>=1.10,<1.11'
    - python: 3.3
      env: DJANGO='django>=1.9,<1.10'

  allow_failures:
    - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'

notifications:
  email: false
